# Generated by Django 4.1.7 on 2023-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_text', models.CharField(max_length=300)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
